# Generated by Django 5.2.7 on 2026-01-01 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_userproductsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceproduct',
            name='ai_recommendation_prompt',
            field=models.TextField(blank=True, help_text='AI推荐产品时使用的描述，帮助AI更好地理解产品特性', verbose_name='AI推荐提示词'),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='coverage_type',
            field=models.CharField(blank=True, help_text='例如：储蓄/重疾/医疗/教育基金/退休规划，多个用逗号分隔', max_length=100, verbose_name='保障类型'),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='产品特点数组，例如：["高额身故保障", "现金价值稳定增长", "可附加重疾保障"]', verbose_name='产品特点列表'),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='min_annual_income',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='建议的最低年收入（台币），例如：500000', max_digits=15, null=True, verbose_name='最低年收入要求'),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='target_age_max',
            field=models.IntegerField(blank=True, help_text='适合的最大年龄，例如：50', null=True, verbose_name='目标年龄段最大值'),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='target_age_min',
            field=models.IntegerField(blank=True, help_text='适合的最小年龄，例如：25', null=True, verbose_name='目标年龄段最小值'),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='target_life_stage',
            field=models.CharField(blank=True, help_text='例如：扶幼保障期/收入成长期/责任高峰期/责任递减期/退休期，多个用逗号分隔', max_length=50, verbose_name='目标人生阶段'),
        ),
    ]
