# Generated by Django 5.2.7 on 2026-01-01 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_insuranceproduct_ai_recommendation_prompt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='例如：35岁IT工程师的家庭保障方案', max_length=200, verbose_name='案例标题')),
                ('life_stage', models.CharField(choices=[('扶幼保障期', '扶幼保障期（25-30岁）'), ('收入成长期', '收入成长期（31-40岁）'), ('责任高峰期', '责任高峰期（41-50岁）'), ('责任递减期', '责任递减期（51-60岁）'), ('退休期', '退休期（60岁以上）')], help_text='客户所处的人生阶段', max_length=50, verbose_name='人生阶段')),
                ('customer_age', models.IntegerField(help_text='案例中客户的年龄', verbose_name='客户年龄')),
                ('annual_income', models.DecimalField(decimal_places=2, help_text='年收入（台币）', max_digits=15, verbose_name='年收入')),
                ('family_structure', models.CharField(help_text='例如：已婚，2个子女（5岁、8岁）', max_length=200, verbose_name='家庭结构')),
                ('insurance_needs', models.TextField(help_text='客户的主要保险需求和关注点', verbose_name='保险需求')),
                ('recommended_products', models.JSONField(default=list, help_text='JSON格式：[{"product_name": "产品名", "company": "公司", "annual_premium": 50000, "coverage_type": "重疾", "reason": "推荐理由"}]', verbose_name='推荐产品列表')),
                ('total_annual_premium', models.DecimalField(decimal_places=2, help_text='所有推荐产品的年缴保费总和（台币）', max_digits=15, verbose_name='年缴保费总额')),
                ('case_image', models.ImageField(blank=True, help_text='案例展示图片', null=True, upload_to='customer_cases/', verbose_name='案例配图')),
                ('case_description', models.TextField(help_text='详细描述案例的保障方案和配置理念', verbose_name='案例详细说明')),
                ('key_points', models.JSONField(blank=True, default=list, help_text='配置方案的关键要点列表，例如：["要点1", "要点2"]', verbose_name='关键要点')),
                ('budget_suggestion', models.CharField(blank=True, help_text='例如：年缴保费: 80,000-120,000 台币', max_length=200, verbose_name='预算建议')),
                ('sort_order', models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, help_text='是否在前端展示此案例', verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '客户案例',
                'verbose_name_plural': '客户案例',
                'db_table': 'customer_cases',
                'ordering': ['sort_order', '-created_at'],
                'indexes': [models.Index(fields=['life_stage', 'is_active'], name='customer_ca_life_st_92c432_idx'), models.Index(fields=['sort_order'], name='customer_ca_sort_or_21ce17_idx')],
            },
        ),
    ]
