# Generated by Django 5.2.7 on 2026-01-19 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_customercase'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(verbose_name='表格编号')),
                ('table_name', models.CharField(max_length=500, verbose_name='表格名称')),
                ('row_count', models.IntegerField(default=0, verbose_name='行数')),
                ('fields', models.TextField(blank=True, default='', verbose_name='基本字段')),
                ('html_source', models.TextField(blank=True, default='', verbose_name='HTML源代码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('plan_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_tables', to='api.plandocument', verbose_name='计划书')),
            ],
            options={
                'verbose_name': '计划书表格',
                'verbose_name_plural': '计划书表格',
                'db_table': 'plan_tables',
                'ordering': ['plan_document', 'table_number'],
                'unique_together': {('plan_document', 'table_number')},
            },
        ),
    ]
