# Generated by Django 5.2.7 on 2026-01-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_plantable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandocument',
            name='processing_stage',
            field=models.CharField(choices=[('pending', '待处理'), ('extracting_tablecontent', '提取表格源代码中'), ('tablecontent_completed', '表格源代码完成'), ('extracting_tablesummary', '分析表格结构中'), ('tablesummary_completed', '表格结构分析完成'), ('extracting_table_html', '提取表格HTML中'), ('extracting_basic_info', '提取基本信息中'), ('basic_info_completed', '基本信息完成'), ('extracting_table', '提取年度价值表中'), ('table_completed', '年度价值表完成'), ('extracting_summary', '提取概要中'), ('all_completed', '全部完成'), ('error', '处理出错')], default='pending', max_length=50, verbose_name='处理阶段'),
        ),
    ]
