# Generated by Django 5.2.7 on 2026-01-23 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_plandocument_processing_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparison_title', models.CharField(default='计划书对比分析', max_length=255, verbose_name='对比标题')),
                ('comparison_result', models.JSONField(blank=True, default=dict, verbose_name='对比数据')),
                ('comparison_summary', models.TextField(blank=True, default='', verbose_name='对比总结')),
                ('status', models.CharField(choices=[('processing', '分析中'), ('completed', '已完成'), ('failed', '失败')], default='processing', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('document1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_as_doc1', to='api.plandocument', verbose_name='计划书1')),
                ('document2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_as_doc2', to='api.plandocument', verbose_name='计划书2')),
                ('document3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparison_as_doc3', to='api.plandocument', verbose_name='计划书3')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建用户')),
            ],
            options={
                'verbose_name': '计划书对比报告',
                'verbose_name_plural': '计划书对比报告',
                'db_table': 'comparison_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
