# Generated by Django 5.2.7 on 2026-01-23 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_comparisonreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonreport',
            name='pdf1_base64',
            field=models.TextField(blank=True, verbose_name='计划书1 PDF Base64'),
        ),
        migrations.AddField(
            model_name='comparisonreport',
            name='pdf1_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='计划书1文件名'),
        ),
        migrations.AddField(
            model_name='comparisonreport',
            name='pdf2_base64',
            field=models.TextField(blank=True, verbose_name='计划书2 PDF Base64'),
        ),
        migrations.AddField(
            model_name='comparisonreport',
            name='pdf2_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='计划书2文件名'),
        ),
        migrations.AddField(
            model_name='comparisonreport',
            name='pdf3_base64',
            field=models.TextField(blank=True, default='', verbose_name='计划书3 PDF Base64'),
        ),
        migrations.AddField(
            model_name='comparisonreport',
            name='pdf3_filename',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='计划书3文件名'),
        ),
        migrations.AddField(
            model_name='comparisonreport',
            name='report_format',
            field=models.CharField(choices=[('html', 'HTML'), ('markdown', 'Markdown')], default='markdown', max_length=10, verbose_name='报告格式'),
        ),
        migrations.AlterField(
            model_name='comparisonreport',
            name='document1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparison_as_doc1', to='api.plandocument', verbose_name='计划书1'),
        ),
        migrations.AlterField(
            model_name='comparisonreport',
            name='document2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparison_as_doc2', to='api.plandocument', verbose_name='计划书2'),
        ),
    ]
