# Generated by Django 5.2.7 on 2026-01-23 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_comparisonreport_pdf1_base64_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf1_name', models.CharField(max_length=255, verbose_name='计划书1文件名')),
                ('pdf1_base64', models.TextField(verbose_name='计划书1 PDF Base64')),
                ('pdf2_name', models.CharField(max_length=255, verbose_name='计划书2文件名')),
                ('pdf2_base64', models.TextField(verbose_name='计划书2 PDF Base64')),
                ('pdf3_name', models.CharField(blank=True, default='', max_length=255, verbose_name='计划书3文件名')),
                ('pdf3_base64', models.TextField(blank=True, default='', verbose_name='计划书3 PDF Base64')),
                ('comparison_report', models.TextField(blank=True, default='', verbose_name='对比报告')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建用户')),
            ],
            options={
                'verbose_name': '计划书对比',
                'verbose_name_plural': '计划书对比',
                'db_table': 'plan_comparisons',
                'ordering': ['-created_at'],
            },
        ),
    ]
