# Generated by Django 5.2.7 on 2026-01-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_change_life_stage_to_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceproduct',
            name='plan_summary',
            field=models.TextField(blank=True, help_text='产品在计划书中的概要描述，用于快速了解产品核心信息', verbose_name='计划书产品概要'),
        ),
        migrations.AlterField(
            model_name='customercase',
            name='annual_income',
            field=models.DecimalField(decimal_places=2, help_text='年收入（港币）', max_digits=15, verbose_name='年收入'),
        ),
        migrations.AlterField(
            model_name='customercase',
            name='budget_suggestion',
            field=models.CharField(blank=True, help_text='例如：年缴保费: 80,000-120,000 港币', max_length=200, verbose_name='预算建议'),
        ),
        migrations.AlterField(
            model_name='customercase',
            name='total_annual_premium',
            field=models.DecimalField(decimal_places=2, help_text='所有推荐产品的年缴保费总和（港币）', max_digits=15, verbose_name='年缴保费总额'),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='min_annual_income',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='建议的最低年收入（港币），例如：500000', max_digits=15, null=True, verbose_name='最低年收入要求'),
        ),
        migrations.AddIndex(
            model_name='customercase',
            index=models.Index(fields=['is_active'], name='customer_ca_is_acti_143f29_idx'),
        ),
    ]
