# Generated by Django 5.2.7 on 2026-01-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_add_plan_summary_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceproduct',
            name='plan_details',
            field=models.TextField(blank=True, help_text='产品计划书的完整详细信息，包括条款、保障范围、理赔流程等详细内容', verbose_name='计划书详情'),
        ),
    ]
