# Generated by Django 5.2.7 on 2026-01-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_add_plan_details_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceproduct',
            name='product_category',
            field=models.CharField(blank=True, help_text='产品类型分类，例如：重疾险、理财、储蓄、医疗险等', max_length=50, verbose_name='产品分类'),
        ),
    ]
