# Generated by Django 5.2.7 on 2026-01-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_add_product_category_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceproduct',
            name='plan_pdf_base64',
            field=models.TextField(blank=True, default='', help_text='存储计划书PDF文件的Base64编码，用于前端下载或预览', verbose_name='计划书PDF Base64编码'),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='product_research_report',
            field=models.TextField(blank=True, default='', help_text='产品的深度研究报告，包括市场分析、竞品对比、投资策略等专业内容', verbose_name='产品研究报告'),
        ),
    ]
