# Generated by Django 5.2.7 on 2026-01-26 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_add_pdf_base64_and_research_report_to_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(blank=True, help_text='例如：5年缴费方案、10年缴费方案', max_length=100, verbose_name='方案名称')),
                ('payment_period', models.IntegerField(help_text='缴费年数，例如：5、10、15、20', verbose_name='缴费年期')),
                ('annual_premium', models.DecimalField(decimal_places=2, help_text='年缴保费金额（港币）', max_digits=15, verbose_name='年缴金额')),
                ('surrender_value_table', models.TextField(blank=True, default='', help_text='JSON格式：[{"year": 1, "guaranteed": 0, "non_guaranteed": 0, "total": 0, "premiums_paid": 10000}, ...]', verbose_name='退保发还金额表')),
                ('death_benefit_table', models.TextField(blank=True, default='', help_text='JSON格式：[{"year": 1, "benefit": 100000}, {"year": 2, "benefit": 150000}, ...]', verbose_name='身故保险赔偿表')),
                ('irr_rate', models.DecimalField(blank=True, decimal_places=2, help_text='年化内部回报率（百分比），例如：5.5 表示5.5%', max_digits=6, null=True, verbose_name='内部回报率（IRR）')),
                ('total_premium', models.DecimalField(blank=True, decimal_places=2, help_text='年缴金额 × 缴费年期', max_digits=15, null=True, verbose_name='总保费')),
                ('plan_description', models.TextField(blank=True, default='', help_text='该缴费方案的详细说明和特点', verbose_name='方案说明')),
                ('is_recommended', models.BooleanField(default=False, help_text='标记为推荐方案会在前端优先显示', verbose_name='是否推荐方案')),
                ('sort_order', models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '产品缴费方案',
                'verbose_name_plural': '产品缴费方案',
                'db_table': 'product_plans',
                'ordering': ['product', 'sort_order', 'payment_period'],
            },
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='annual_premium',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='⚠️ 已废弃：请使用 ProductPlan 关联表管理不同年缴金额', max_digits=15, null=True, verbose_name='年缴金额（已废弃）'),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='death_benefit_table',
            field=models.TextField(blank=True, default='', help_text='⚠️ 已废弃：请使用 ProductPlan 关联表管理身故赔偿表', verbose_name='身故保险赔偿表（已废弃）'),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='payment_period',
            field=models.IntegerField(blank=True, help_text='⚠️ 已废弃：请使用 ProductPlan 关联表管理不同缴费年期', null=True, verbose_name='缴费年期（已废弃）'),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='surrender_value_table',
            field=models.TextField(blank=True, default='', help_text='⚠️ 已废弃：请使用 ProductPlan 关联表管理退保价值表', verbose_name='退保发还金额表（已废弃）'),
        ),
        migrations.AddField(
            model_name='productplan',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='api.insuranceproduct', verbose_name='所属产品'),
        ),
        migrations.AddIndex(
            model_name='productplan',
            index=models.Index(fields=['product', 'is_active'], name='product_pla_product_1962e0_idx'),
        ),
        migrations.AddIndex(
            model_name='productplan',
            index=models.Index(fields=['product', 'payment_period'], name='product_pla_product_82e07b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productplan',
            unique_together={('product', 'payment_period')},
        ),
    ]
