# Generated by Django 5.2.7 on 2026-01-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_create_product_plan_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceproduct',
            name='supported_payment_periods',
            field=models.CharField(blank=True, default='', help_text='产品支持的缴费年期选项，多个用逗号分隔，例如：1年,2年,5年,趸缴', max_length=200, verbose_name='支持的缴费年期'),
        ),
    ]
