# Generated by Django 5.2.7 on 2026-01-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_add_supported_payment_periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercase',
            name='category',
            field=models.CharField(default='未分类', help_text='文章分类，例如：基础认知、重疾险、理财储蓄、理赔售后等', max_length=50, verbose_name='文章分类'),
        ),
    ]
