# Generated by Django 5.2.7 on 2026-01-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_remove_customercase_customer_ca_life_st_92c432_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercase',
            name='content',
            field=models.TextField(blank=True, default='', help_text='公司新闻/文章的完整内容（Markdown格式），用于替代case_description字段', verbose_name='文章内容'),
        ),
    ]
