# Generated by Django 5.2.7 on 2026-02-02 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_remove_customercase_customer_ca_life_st_92c432_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='宣传材料的标题，例如：产品小册子、产品新闻、产品说明', max_length=200, verbose_name='宣传标题')),
                ('content_type', models.CharField(choices=[('news', '新闻'), ('brochure', '产品小册子'), ('guide', '产品说明'), ('video', '视频'), ('article', '文章'), ('other', '其他')], default='news', help_text='宣传材料的类型', max_length=50, verbose_name='内容类型')),
                ('description', models.TextField(blank=True, help_text='宣传材料的简要描述', verbose_name='描述')),
                ('url', models.URLField(blank=True, help_text='外部链接，如新闻链接、视频链接等', max_length=500, verbose_name='链接地址')),
                ('pdf_file', models.FileField(blank=True, help_text='上传产品小册子PDF文件', null=True, upload_to='product_promotions/', verbose_name='PDF文件')),
                ('pdf_base64', models.TextField(blank=True, default='', help_text='PDF文件的Base64编码，用于前端下载或预览', verbose_name='PDF Base64编码')),
                ('thumbnail', models.ImageField(blank=True, help_text='宣传材料的缩略图', null=True, upload_to='product_promotions/thumbnails/', verbose_name='缩略图')),
                ('published_date', models.DateField(blank=True, help_text='宣传材料的发布日期', null=True, verbose_name='发布日期')),
                ('is_active', models.BooleanField(default=True, help_text='是否在前端显示此宣传材料', verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '产品宣传材料',
                'verbose_name_plural': '产品宣传材料',
                'db_table': 'product_promotions',
                'ordering': ['product', 'sort_order', '-published_date'],
            },
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='url',
            field=models.URLField(blank=True, help_text='产品的官方网站链接地址', max_length=500, verbose_name='官方产品链接'),
        ),
        migrations.AddField(
            model_name='productpromotion',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='api.insuranceproduct', verbose_name='所属产品'),
        ),
        migrations.AddIndex(
            model_name='productpromotion',
            index=models.Index(fields=['product', 'is_active'], name='product_pro_product_865ed9_idx'),
        ),
        migrations.AddIndex(
            model_name='productpromotion',
            index=models.Index(fields=['content_type'], name='product_pro_content_72c2fa_idx'),
        ),
    ]
