# Generated by Django 5.2.7 on 2026-02-02 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_add_product_url_and_promotions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='新闻或宣传材料的标题', max_length=200, verbose_name='标题')),
                ('content_type', models.CharField(choices=[('news', '公司新闻'), ('announcement', '公司公告'), ('brochure', '公司小册子'), ('video', '视频'), ('article', '文章'), ('press_release', '新闻稿'), ('report', '年度报告'), ('other', '其他')], default='news', help_text='内容的类型', max_length=50, verbose_name='内容类型')),
                ('description', models.TextField(blank=True, help_text='新闻或材料的简要描述', verbose_name='描述')),
                ('content', models.TextField(blank=True, help_text='新闻或材料的完整正文内容（支持HTML）', verbose_name='正文内容')),
                ('url', models.URLField(blank=True, help_text='外部新闻链接、视频链接等', max_length=500, verbose_name='外部链接')),
                ('pdf_file', models.FileField(blank=True, help_text='上传PDF文件（如公司年报、小册子等）', null=True, upload_to='company_news/', verbose_name='PDF文件')),
                ('pdf_base64', models.TextField(blank=True, default='', help_text='PDF文件的Base64编码，用于前端下载或预览', verbose_name='PDF Base64编码')),
                ('thumbnail', models.ImageField(blank=True, help_text='新闻或材料的缩略图', null=True, upload_to='company_news/thumbnails/', verbose_name='缩略图')),
                ('published_date', models.DateField(blank=True, help_text='新闻或材料的发布日期', null=True, verbose_name='发布日期')),
                ('is_active', models.BooleanField(default=True, help_text='是否在前端显示此内容', verbose_name='是否启用')),
                ('is_featured', models.BooleanField(default=False, help_text='标记为精选内容将优先显示', verbose_name='是否精选')),
                ('sort_order', models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '公司新闻与宣传',
                'verbose_name_plural': '公司新闻与宣传',
                'db_table': 'company_news',
                'ordering': ['company', '-is_featured', 'sort_order', '-published_date'],
            },
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='website_url',
            field=models.URLField(blank=True, help_text='保险公司的官方网站链接地址', max_length=500, verbose_name='公司官网'),
        ),
        migrations.AddField(
            model_name='companynews',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='api.insurancecompany', verbose_name='所属公司'),
        ),
        migrations.AddIndex(
            model_name='companynews',
            index=models.Index(fields=['company', 'is_active'], name='company_new_company_2311e9_idx'),
        ),
        migrations.AddIndex(
            model_name='companynews',
            index=models.Index(fields=['content_type'], name='company_new_content_7b2de7_idx'),
        ),
        migrations.AddIndex(
            model_name='companynews',
            index=models.Index(fields=['is_featured'], name='company_new_is_feat_daac2f_idx'),
        ),
        migrations.AddIndex(
            model_name='companynews',
            index=models.Index(fields=['published_date'], name='company_new_publish_a45403_idx'),
        ),
    ]
