# Generated by Django 5.2.7 on 2026-02-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_companynews_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customercase',
            name='customer_ca_life_st_92c432_idx',
        ),
        migrations.AddField(
            model_name='productplan',
            name='is_withdrawal',
            field=models.BooleanField(default=False, help_text='是否包含提取功能', verbose_name='是否提取'),
        ),
    ]
