# Generated by Django 5.2.7 on 2026-02-05 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_add_is_withdrawal_to_product_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productplan',
            name='is_withdrawal',
        ),
        migrations.CreateModel(
            name='DailyUsageQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='日期')),
                ('upload_count', models.IntegerField(default=0, verbose_name='当日上传次数')),
                ('max_daily_limit', models.IntegerField(default=4, verbose_name='每日最大限制')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '每日使用限额',
                'verbose_name_plural': '每日使用限额',
                'db_table': 'daily_usage_quotas',
                'indexes': [models.Index(fields=['user', 'date'], name='daily_usage_user_id_f8896b_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
