# Generated by Django 5.2.7 on 2026-02-11 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_remove_productplan_is_withdrawal_dailyusagequota'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceproduct',
            name='product_details',
            field=models.JSONField(blank=True, default=dict, help_text='产品的详细属性信息（键值对），例如：{"投保年龄": "0-75岁", "货币": "9种", "可转换币种": "美元/人民币/港币/...", "可转换时间": "第3个保单周年日起，1次/年", "最低投保额要求": "不可低于若干额度", "新造保费折扣": "保费5%+首年保费1%回赠", "更改受保人": "可", "第二持有人": "可", "保单贷款": "保证现金价值90%", "保费锁定": "无", "分红基制": "英式分红", "分红期限/分红检讨周期": "第10个保单年度起每年公布", "身故赔偿选项": "一笔过/分期/...", "赔偿方式": "一笔过/分期25%+50%", "公司成立年份": "1846年", "代表信贷评级": "A+ / A2"}', verbose_name='产品详细信息'),
        ),
    ]
