# Generated by Django 5.2.7 on 2026-03-09 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_add_product_details_to_insuranceproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesScriptCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例如：担心安全性', max_length=50, verbose_name='场景名称')),
                ('icon', models.CharField(default='💬', max_length=10, verbose_name='图标(emoji)')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='场景描述')),
                ('sort_order', models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '话术场景分类',
                'verbose_name_plural': '话术场景分类',
                'db_table': 'sales_script_category',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SalesScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='简短描述这条话术的用途', max_length=200, verbose_name='话术标题')),
                ('customer_question', models.TextField(help_text='客户通常会说的话或问的问题', verbose_name='客户常问')),
                ('script_content', models.TextField(help_text='经纪人推荐的回应内容', verbose_name='推荐话术')),
                ('follow_up_question', models.TextField(blank=True, help_text='用于引导客户深入的跟进问题', verbose_name='跟进问题')),
                ('key_points', models.JSONField(blank=True, default=list, help_text='话术中的关键点', verbose_name='话术要点')),
                ('applicable_product_type', models.CharField(choices=[('all', '全部产品'), ('savings', '储蓄险'), ('critical_illness', '重疾险'), ('annuity', '年金险'), ('whole_life', '终身寿险')], default='all', max_length=30, verbose_name='适用产品类型')),
                ('applicable_customer_type', models.CharField(choices=[('all', '全部客群'), ('young_family', '年轻家庭'), ('high_net_worth', '高净值客户'), ('education', '子女教育'), ('retirement', '养老规划'), ('asset_inheritance', '资产传承')], default='all', max_length=30, verbose_name='适用客群')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否精选')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('view_count', models.IntegerField(default=0, verbose_name='查看次数')),
                ('copy_count', models.IntegerField(default=0, verbose_name='复制次数')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='api.salesscriptcategory', verbose_name='所属场景')),
            ],
            options={
                'verbose_name': '营销话术',
                'verbose_name_plural': '营销话术',
                'db_table': 'sales_script',
                'ordering': ['-is_featured', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SalesScriptFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='api.salesscript', verbose_name='话术')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_favorites', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '话术收藏',
                'verbose_name_plural': '话术收藏',
                'db_table': 'sales_script_favorite',
            },
        ),
        migrations.AddIndex(
            model_name='salesscript',
            index=models.Index(fields=['category', 'is_active'], name='sales_scrip_categor_3cba91_idx'),
        ),
        migrations.AddIndex(
            model_name='salesscript',
            index=models.Index(fields=['applicable_product_type'], name='sales_scrip_applica_169ae7_idx'),
        ),
        migrations.AddIndex(
            model_name='salesscript',
            index=models.Index(fields=['applicable_customer_type'], name='sales_scrip_applica_cb317c_idx'),
        ),
        migrations.AddIndex(
            model_name='salesscript',
            index=models.Index(fields=['is_featured'], name='sales_scrip_is_feat_d3028e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salesscriptfavorite',
            unique_together={('user', 'script')},
        ),
    ]
